"""PH-34 add board_workflows junction table

Revision ID: 2e0ab0aa83ce
Revises: f53394ff48bb
Create Date: 2026-05-20 12:31:28.055307
"""

from alembic import op
import sqlalchemy as sa


revision = '2e0ab0aa83ce'
down_revision = 'f53394ff48bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board_workflows',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('board_id', sa.Uuid(), nullable=False),
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('board_id', 'is_active', name='uq_board_active_workflow')
    )

    # Populate junction table with existing board.workflow_id relationships
    # This ensures all existing boards maintain their current workflow
    op.execute("""
        INSERT INTO board_workflows (id, board_id, workflow_id, is_active, created_at, updated_at)
        SELECT
            gen_random_uuid() as id,
            boards.id as board_id,
            boards.workflow_id,
            true as is_active,
            boards.created_at,
            boards.updated_at
        FROM boards
        WHERE boards.workflow_id IS NOT NULL
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('board_workflows')
    # ### end Alembic commands ###
